package chatgptcookie

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"testing"
	"time"
)

func TestParseCookieInputSupportsCookieEditorFormats(t *testing.T) {
	tests := []struct {
		name       string
		input      string
		wantFormat string
		wantDomain string
	}{
		{
			name: "json",
			input: `[
				{
					"domain": ".chatgpt.com",
					"expirationDate": 1999999999.75,
					"hostOnly": false,
					"name": "__Secure-next-auth.session-token",
					"path": "/",
					"secure": true,
					"value": "json-token"
				}
			]`,
			wantFormat: "Cookie-Editor JSON",
			wantDomain: ".chatgpt.com",
		},
		{
			name: "netscape",
			input: strings.Join([]string{
				"# Netscape HTTP Cookie File",
				"# This file was generated by Cookie-Editor",
				"#HttpOnly_.chatgpt.com\tTRUE\t/\tTRUE\t1999999999\t__Secure-next-auth.session-token\tnetscape-token",
			}, "\n"),
			wantFormat: "Netscape",
			wantDomain: ".chatgpt.com",
		},
		{
			name:       "header",
			input:      "cookie: __Secure-next-auth.session-token=header-token; cf_clearance=clearance",
			wantFormat: "Header String",
			wantDomain: "",
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			cookies, format, err := parseCookieInput([]byte(tc.input))
			if err != nil {
				t.Fatalf("parseCookieInput: %v", err)
			}
			if format != tc.wantFormat {
				t.Fatalf("format = %q, want %q", format, tc.wantFormat)
			}
			if len(cookies) == 0 {
				t.Fatal("no cookies parsed")
			}
			if cookies[0].Domain != tc.wantDomain {
				t.Fatalf("domain = %q, want %q", cookies[0].Domain, tc.wantDomain)
			}
			if !isSessionCookie(cookies[0].Name) {
				t.Fatalf("session cookie not recognized: %q", cookies[0].Name)
			}
		})
	}
}

func TestParseJSONCookiesSupportsWrapperAndSingleCookie(t *testing.T) {
	wrapped, err := parseJSONCookies([]byte(`{
		"cookies": [
			{"domain": ".chatgpt.com", "name": "__Secure-authjs.session-token.0", "value": "part-0"}
		]
	}`))
	if err != nil {
		t.Fatalf("parse wrapped: %v", err)
	}
	if len(wrapped) != 1 || wrapped[0].Value != "part-0" {
		t.Fatalf("wrapped = %#v", wrapped)
	}

	single, err := parseJSONCookies([]byte(
		`{"domain":".chatgpt.com","name":"next-auth.session-token","value":"single"}`,
	))
	if err != nil {
		t.Fatalf("parse single: %v", err)
	}
	if len(single) != 1 || single[0].Value != "single" {
		t.Fatalf("single = %#v", single)
	}
}

func TestParseCookieInputRejectsHeaderInjection(t *testing.T) {
	_, _, err := parseCookieInput([]byte(
		"__Secure-next-auth.session-token=secret\r\nX-Leak: true",
	))
	if err == nil || !strings.Contains(err.Error(), "newlines") {
		t.Fatalf("header injection should fail, got: %v", err)
	}
}

func TestCookiesForURLFiltersScopeExpiryAndKeepsChunks(t *testing.T) {
	now := time.Unix(1_800_000_000, 0).UTC()
	target, _ := url.Parse(DefaultSessionEndpoint)
	cookies := []browserCookie{
		{
			Domain: ".chatgpt.com", Path: "/", Secure: true,
			Name: "__Secure-authjs.session-token.1", Value: "part-1",
			ExpiresAt: now.Add(time.Hour).Unix(),
		},
		{
			Domain: ".chatgpt.com", Path: "/", Secure: true,
			Name: "__Secure-authjs.session-token.0", Value: "part-0",
			ExpiresAt: now.Add(time.Hour).Unix(),
		},
		{
			Domain: ".chatgpt.com", Path: "/", Secure: true,
			Name: "__Secure-authjs.session-token.10", Value: "part-10",
			ExpiresAt: now.Add(time.Hour).Unix(),
		},
		{
			Domain: ".chatgpt.com", Path: "/", Secure: true,
			Name: "__Secure-authjs.session-token.2", Value: "part-2",
			ExpiresAt: now.Add(time.Hour).Unix(),
		},
		{
			Domain: ".chatgpt.com", Path: "/", Secure: true,
			Name: "cf_clearance", Value: "clearance",
			ExpiresAt: now.Add(time.Hour).Unix(),
		},
		{
			Domain: ".chatgpt.com", Path: "/", Secure: true,
			Name: "expired", Value: "old",
			ExpiresAt: now.Add(-time.Second).Unix(),
		},
		{
			Domain: ".example.com", Path: "/", Secure: true,
			Name: "unrelated", Value: "wrong-domain",
			ExpiresAt: now.Add(time.Hour).Unix(),
		},
		{
			Domain: ".chatgpt.com", Path: "/backend-api", Secure: true,
			Name: "wrong-path", Value: "not-for-session",
			ExpiresAt: now.Add(time.Hour).Unix(),
		},
	}

	filtered, err := cookiesForURL(cookies, target, now)
	if err != nil {
		t.Fatalf("cookiesForURL: %v", err)
	}
	header, err := buildCookieHeader(filtered)
	if err != nil {
		t.Fatalf("buildCookieHeader: %v", err)
	}
	for _, want := range []string{
		"__Secure-authjs.session-token.0=part-0",
		"__Secure-authjs.session-token.1=part-1",
		"__Secure-authjs.session-token.2=part-2",
		"__Secure-authjs.session-token.10=part-10",
		"cf_clearance=clearance",
	} {
		if !strings.Contains(header, want) {
			t.Errorf("header missing %q: %s", want, header)
		}
	}
	for _, notWant := range []string{"expired", "wrong-domain", "wrong-path"} {
		if strings.Contains(header, notWant) {
			t.Errorf("header should not contain %q: %s", notWant, header)
		}
	}
	if strings.Index(header, ".0=part-0") > strings.Index(header, ".1=part-1") {
		t.Fatalf("chunk order is wrong: %s", header)
	}
	if strings.Index(header, ".2=part-2") > strings.Index(header, ".10=part-10") {
		t.Fatalf("multi-digit chunk order is wrong: %s", header)
	}
}

func TestSessionCookieFamilyOnlyAcceptsNumericChunks(t *testing.T) {
	for _, name := range []string{
		"__Secure-next-auth.session-token",
		"__Secure-next-auth.session-token.0",
		"authjs.session-token.12",
	} {
		if !isSessionCookie(name) {
			t.Errorf("should recognize %q", name)
		}
	}
	for _, name := range []string{
		"__Secure-next-auth.csrf-token",
		"__Secure-next-auth.session-token.bad",
		"prefix__Secure-next-auth.session-token",
	} {
		if isSessionCookie(name) {
			t.Errorf("should not recognize %q", name)
		}
	}
}

func TestValidateSessionEndpointRestrictsCookieDestination(t *testing.T) {
	for _, raw := range []string{
		DefaultSessionEndpoint,
		LegacySessionEndpoint,
		"https://auth.openai.com/custom/session",
	} {
		if _, err := validateSessionEndpoint(raw); err != nil {
			t.Errorf("official endpoint %q rejected: %v", raw, err)
		}
	}

	for _, raw := range []string{
		"http://chatgpt.com/api/auth/session",
		"https://chatgpt.com.evil.example/api/auth/session",
		"https://evilopenai.com/api/auth/session",
		"https://user:pass@chatgpt.com/api/auth/session",
		"https://chatgpt.com:8443/api/auth/session",
	} {
		if _, err := validateSessionEndpoint(raw); err == nil {
			t.Errorf("dangerous endpoint %q should be rejected", raw)
		}
	}
}

func TestConvertBuildsSanitizedImportCredential(t *testing.T) {
	now := time.Date(2026, 8, 3, 6, 0, 0, 0, time.UTC)
	expiry := now.Add(2 * time.Hour)
	accessToken := testJWT(t, expiry)
	const cookieSecret = "browser-session-secret"
	const responseSessionSecret = "must-not-be-exported"

	var gotCookie, gotUA, gotReferer string
	client := &http.Client{Transport: roundTripFunc(func(r *http.Request) (*http.Response, error) {
		gotCookie = r.Header.Get("Cookie")
		gotUA = r.Header.Get("User-Agent")
		gotReferer = r.Header.Get("Referer")
		body := fmt.Sprintf(`{
			"user":{"id":"user-1","name":"Tester","email":"person@example.com","private":"drop-me"},
			"account":{"id":"acct-1","planType":"plus","private":"drop-me"},
			"accessToken":%q,
			"sessionToken":%q,
			"expires":"2026-08-10T00:00:00Z",
			"authProvider":"auth0"
		}`, accessToken, responseSessionSecret)
		return &http.Response{
			StatusCode: http.StatusOK,
			Header:     make(http.Header),
			Body:       io.NopCloser(strings.NewReader(body)),
			Request:    r,
		}, nil
	})}

	result, err := Convert(
		context.Background(),
		client,
		[]byte("__Secure-next-auth.session-token="+cookieSecret+"; cf_clearance=ok"),
		Options{Now: now, UserAgent: "test-agent"},
	)
	if err != nil {
		t.Fatalf("Convert: %v", err)
	}
	if gotCookie != "__Secure-next-auth.session-token="+cookieSecret+"; cf_clearance=ok" {
		t.Fatalf("Cookie = %q", gotCookie)
	}
	if gotUA != "test-agent" {
		t.Fatalf("User-Agent = %q", gotUA)
	}
	if gotReferer != "https://chatgpt.com/" {
		t.Fatalf("Referer = %q", gotReferer)
	}
	if !result.TokenExpiresAt.Equal(expiry) {
		t.Fatalf("expiry = %s, want %s", result.TokenExpiresAt, expiry)
	}
	if result.Credential.AccessToken != accessToken ||
		result.Credential.ExpiresAt != expiry.Format(time.RFC3339) {
		t.Fatalf("credential token/expiry mismatch: %#v", result.Credential)
	}
	if result.Credential.User["email"] != "person@example.com" ||
		result.Credential.Account["planType"] != "plus" {
		t.Fatalf("identity not retained: %#v", result.Credential)
	}
	if _, ok := result.Credential.User["private"]; ok {
		t.Fatalf("unknown user field retained: %#v", result.Credential.User)
	}

	encoded, err := json.Marshal(result.Credential)
	if err != nil {
		t.Fatal(err)
	}
	for _, secret := range []string{cookieSecret, responseSessionSecret, "drop-me"} {
		if strings.Contains(string(encoded), secret) {
			t.Fatalf("credential leaked %q: %s", secret, encoded)
		}
	}
}

func TestConvertDisablesRedirectsWithoutMutatingSharedClient(t *testing.T) {
	var targetHits int
	client := &http.Client{
		Transport: roundTripFunc(func(r *http.Request) (*http.Response, error) {
			if r.URL.Host == "evil.example" {
				targetHits++
			}
			return &http.Response{
				StatusCode: http.StatusFound,
				Header:     http.Header{"Location": []string{"https://evil.example/steal"}},
				Body:       io.NopCloser(strings.NewReader("redirect")),
				Request:    r,
			}, nil
		}),
		CheckRedirect: func(_ *http.Request, _ []*http.Request) error {
			t.Fatal("the caller's redirect policy must not be invoked")
			return nil
		},
	}

	_, err := Convert(
		context.Background(),
		client,
		[]byte("__Secure-next-auth.session-token=secret"),
		Options{Now: time.Now()},
	)
	if err == nil || KindOf(err) != ErrorSessionRejected {
		t.Fatalf("redirect should be rejected, got: %v", err)
	}
	if targetHits != 0 {
		t.Fatalf("redirect target was requested %d times", targetHits)
	}
	if client.CheckRedirect == nil {
		t.Fatal("shared client was mutated")
	}
}

func TestExchangeSessionDoesNotLeakErrorBody(t *testing.T) {
	const canary = "response-body-secret"
	client := &http.Client{Transport: roundTripFunc(func(r *http.Request) (*http.Response, error) {
		return &http.Response{
			StatusCode: http.StatusForbidden,
			Header:     make(http.Header),
			Body:       io.NopCloser(strings.NewReader(`{"secret":"` + canary + `"}`)),
			Request:    r,
		}, nil
	})}
	endpoint, _ := url.Parse(DefaultSessionEndpoint)
	_, _, err := exchangeSession(
		context.Background(),
		client,
		endpoint,
		"session=secret",
		"test-agent",
		time.Now(),
	)
	if err == nil {
		t.Fatal("403 should fail")
	}
	if strings.Contains(err.Error(), canary) {
		t.Fatalf("error leaked response body: %v", err)
	}
	if KindOf(err) != ErrorSessionRejected {
		t.Fatalf("kind = %q", KindOf(err))
	}
}

func TestInvalidCookieErrorsDoNotEchoSubmittedSecrets(t *testing.T) {
	const secret = "browser-session-secret-canary"
	for _, raw := range []string{
		secret,
		secret + " bad=value",
		"valid=" + secret + "\nInjected: value",
	} {
		_, _, err := parseCookieInput([]byte(raw))
		if err == nil {
			t.Fatalf("input %q should fail", raw)
		}
		if strings.Contains(err.Error(), secret) {
			t.Fatalf("error leaked submitted cookie material: %v", err)
		}
	}
}

func TestConvertRejectsOversizedUserAgentBeforeSendingCookies(t *testing.T) {
	called := false
	client := &http.Client{Transport: roundTripFunc(func(r *http.Request) (*http.Response, error) {
		called = true
		return nil, errors.New("unexpected request")
	})}
	_, err := Convert(
		context.Background(),
		client,
		[]byte("__Secure-next-auth.session-token=secret"),
		Options{UserAgent: strings.Repeat("x", MaxUserAgentBytes+1)},
	)
	if err == nil || KindOf(err) != ErrorInvalidInput {
		t.Fatalf("oversized User-Agent should be invalid, got %v", err)
	}
	if called {
		t.Fatal("cookies were sent before User-Agent validation")
	}
}

type roundTripFunc func(*http.Request) (*http.Response, error)

func (f roundTripFunc) RoundTrip(req *http.Request) (*http.Response, error) {
	return f(req)
}

func testJWT(t *testing.T, expiry time.Time) string {
	t.Helper()
	header, err := json.Marshal(map[string]any{"alg": "none", "typ": "JWT"})
	if err != nil {
		t.Fatal(err)
	}
	body, err := json.Marshal(map[string]any{"exp": expiry.Unix()})
	if err != nil {
		t.Fatal(err)
	}
	return base64.RawURLEncoding.EncodeToString(header) + "." +
		base64.RawURLEncoding.EncodeToString(body) + ".signature"
}
